<?php
namespace app\index\controller;

use think\Controller;
use think\Db;
use think\Log;
use think\Request;

class Index extends Controller
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        // 响应头设置 我们就是通过设置header来跨域的 这就主要代码了 定义行为只是为了前台每次请求都能走这段代码
// 指定允许其他域名访问
        header('Access-Control-Allow-Origin:http://localhost:9528');
// 响应类型
        header('Access-Control-Allow-Methods:"GET, POST, PUT, DELETE, OPTIONS, HEAD"');
// 响应头设置
        header("Access-Control-Allow-Headers:Content-Type,Access-Control-Allow-Headers,Content-Length,Accept,Authorization,X-Requested-With,x-token");

        header("Access-Control-Allow-Credentials:true");
    }


    public function index()
    {
        return 'GO OUT';
    }

    public function testSupplier()
    {
        $supplierList = Db::name("supplier")->select();
        Log::error($supplierList);
        return returnState(20000,'msg',$supplierList);
    }
}
